name: Build & Publish Presentation with reveal-md

on: workflow_dispatch

jobs:
  release:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies & Build Presentation
        run: |
          sudo npm install -g reveal-md puppeteer --unsafe-perm
          which chrome
          sudo DEBUG=reveal-md reveal-md test_presentation.md --print test_slides.pdf --puppeteer-chromium-executable $CHROMIUM_BIN
      - name: Publish pdf slides
        run: |
          git config user.name github-actions
          git config user.email triznam@si.edu
          git add .
          git commit -m "added slide pdf"
          git push
