name: Build & Publish Presentation with reveal-md

on: workflow_dispatch

jobs:
  release:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies & Build Presentation
        run: sudo npm install -g reveal-md puppeteer --unsafe-perm
      - name: Build presentation pdf slides
        run: DEBUG=reveal-md reveal-md test_presentation.md --print test_slides.pdf
      - name: Publish pdf slides
        run: |
          git config user.name github-actions
          git config user.email triznam@si.edu
          git add .
          git commit -m "added slide pdf"
          git push
      - name: Build presentation slides HTML
        run: DEBUG=reveal-md reveal-md test_presentation.md --static _slides
      # Push the site's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_slides
